package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	colorsort "github.com/wricardo/colorsortgame"
	"github.com/wricardo/colorsortgame/graphqlapi/graph/model"
)

// NewGame is the resolver for the newGame field.
func (r *mutationResolver) NewGame(ctx context.Context, levelID int32) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	level, err := colorsort.FindLevel(r.levels, int(levelID))
	if err != nil {
		return nil, err
	}

	res := colorsort.Solve(level)
	if !res.Unknown && !res.Solvable {
		return nil, fmt.Errorf("level %d is not solvable, refusing to start", levelID)
	}

	s := colorsort.NewSave(level, "")
	id := uuid.NewString()
	r.games[id] = s
	return r.toModelGame(id, s), nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, gameID string, from int32, to int32) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	s, ok := r.games[gameID]
	if !ok {
		return nil, fmt.Errorf("game %q not found", gameID)
	}
	if err := s.ApplyMove(int(from), int(to)); err != nil {
		return nil, err
	}
	r.publish(gameID, s)
	return r.toModelGame(gameID, s), nil
}

// MoveBulk is the resolver for the moveBulk field.
func (r *mutationResolver) MoveBulk(ctx context.Context, gameID string, moves string) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	s, ok := r.games[gameID]
	if !ok {
		return nil, fmt.Errorf("game %q not found", gameID)
	}

	tuples, err := colorsort.ParseMoves(moves)
	if err != nil {
		return nil, err
	}

	for i, m := range tuples {
		if err := s.ApplyMove(m.From, m.To); err != nil {
			return nil, fmt.Errorf("move %d (%d-%d): %w", i+1, m.From, m.To, err)
		}
		if s.Solved || s.Stuck {
			break
		}
	}

	r.publish(gameID, s)
	return r.toModelGame(gameID, s), nil
}

// Undo is the resolver for the undo field.
func (r *mutationResolver) Undo(ctx context.Context, gameID string) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	s, ok := r.games[gameID]
	if !ok {
		return nil, fmt.Errorf("game %q not found", gameID)
	}
	if err := s.Undo(); err != nil {
		return nil, err
	}
	r.publish(gameID, s)
	return r.toModelGame(gameID, s), nil
}

// ResetGame is the resolver for the resetGame field.
func (r *mutationResolver) ResetGame(ctx context.Context, gameID string) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	s, ok := r.games[gameID]
	if !ok {
		return nil, fmt.Errorf("game %q not found", gameID)
	}
	level, err := colorsort.FindLevel(r.levels, s.LevelID)
	if err != nil {
		return nil, err
	}

	fresh := colorsort.NewSave(level, "")
	r.games[gameID] = fresh
	r.publish(gameID, fresh)
	return r.toModelGame(gameID, fresh), nil
}

// Levels is the resolver for the levels field.
func (r *queryResolver) Levels(ctx context.Context, difficulty *model.Difficulty) ([]*model.Level, error) {
	out := make([]*model.Level, 0, len(r.levels.Levels))
	for i := range r.levels.Levels {
		lvl := &r.levels.Levels[i]
		if difficulty != nil && toDifficulty(lvl.Difficulty) != *difficulty {
			continue
		}
		out = append(out, toModelLevel(lvl))
	}
	return out, nil
}

// Level is the resolver for the level field.
func (r *queryResolver) Level(ctx context.Context, id int32) (*model.Level, error) {
	level, err := colorsort.FindLevel(r.levels, int(id))
	if err != nil {
		return nil, err
	}
	return toModelLevel(level), nil
}

// Solvable is the resolver for the solvable field.
func (r *queryResolver) Solvable(ctx context.Context, levelID int32) (*model.SolveResult, error) {
	level, err := colorsort.FindLevel(r.levels, int(levelID))
	if err != nil {
		return nil, err
	}

	res := colorsort.Solve(level)
	return &model.SolveResult{
		Level:    levelID,
		Solvable: res.Solvable,
		Unknown:  res.Unknown,
	}, nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	s, ok := r.games[id]
	if !ok {
		return nil, fmt.Errorf("game %q not found", id)
	}
	return r.toModelGame(id, s), nil
}

// GameUpdated is the resolver for the gameUpdated field.
func (r *subscriptionResolver) GameUpdated(ctx context.Context, gameID string) (<-chan *model.Game, error) {
	r.mu.Lock()
	_, ok := r.games[gameID]
	r.mu.Unlock()
	if !ok {
		return nil, fmt.Errorf("game %q not found", gameID)
	}

	saves, unsubscribe := r.subscribe(gameID)
	out := make(chan *model.Game, 1)

	go func() {
		defer close(out)
		defer unsubscribe()
		for {
			select {
			case <-ctx.Done():
				return
			case g, ok := <-saves:
				if !ok {
					return
				}
				select {
				case out <- g:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
