// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Game struct {
	ID         string     `json:"id"`
	LevelID    int32      `json:"levelId"`
	Difficulty Difficulty `json:"difficulty"`
	Capacity   int32      `json:"capacity"`
	Tubes      [][]string `json:"tubes"`
	Moves      int32      `json:"moves"`
	History    []*Move    `json:"history"`
	Solved     bool       `json:"solved"`
	Stuck      bool       `json:"stuck"`
}

type Level struct {
	ID           int32      `json:"id"`
	Difficulty   Difficulty `json:"difficulty"`
	TubeCapacity int32      `json:"tubeCapacity"`
	Tubes        [][]string `json:"tubes"`
}

type Move struct {
	From int32 `json:"from"`
	To   int32 `json:"to"`
}

type Mutation struct {
}

type Query struct {
}

type SolveResult struct {
	Level    int32    `json:"level"`
	Solvable bool     `json:"solvable"`
	Unknown  bool     `json:"unknown"`
	MinMoves *int32   `json:"minMoves,omitempty"`
	Path     []string `json:"path,omitempty"`
}

type Difficulty string

const (
	DifficultyEasy   Difficulty = "EASY"
	DifficultyMedium Difficulty = "MEDIUM"
	DifficultyHard   Difficulty = "HARD"
)

var AllDifficulty = []Difficulty{
	DifficultyEasy,
	DifficultyMedium,
	DifficultyHard,
}

func (e Difficulty) IsValid() bool {
	switch e {
	case DifficultyEasy, DifficultyMedium, DifficultyHard:
		return true
	}
	return false
}

func (e Difficulty) String() string {
	return string(e)
}

func (e *Difficulty) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Difficulty(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Difficulty", str)
	}
	return nil
}

func (e Difficulty) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Difficulty) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Difficulty) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
